gcp_credentials_file = "../../../modified-link-444013-i9-6d4e030f9f20.json"
project_id           = "modified-link-444013-i9"
region               = "europe-central2"
artifact_repository_id = "my-artifact-repository"
cloud_run_service_name = "my-cloud-run-service"
docker_image = "time-service:latest"
